spring:
  application:
    name: astd
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: prod
  jackson:
    serialization:
      write_dates_as_timestamps: false
    mapper:
      default_view_inclusion: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  mvc:
    favicon:
      enabled: false

  #    security:
  #              user:
  #                    name: test
  #                    password: 1
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jmx:
    default-domain: astd

server:
  servlet:
    session:
      cookie:
        http-only: true
application:
  #              base-path: D:/WORK/astd/src/main/resources/static/
  base-path: \\10.50.25.236\pub\ASTD
  storage-path: D:/WORK/astd/src/main/resources/static/storage/
  ecp-algorithm: AvBelT
  ecp-providers:
    - by.avest.certstore.AvCertStoreProvider
    - by.avest.crypto.pkcs11.provider.avtoken.AvTokenProvider
